FROM liaozhiming/vue_tuiwen:latest-assets AS assets

# detail https://github.com/lipanski/docker-static-website/blob/master/Dockerfile
FROM lipanski/docker-static-website

WORKDIR /home/static

COPY --from=assets /app/* /home/static
COPY server/httpd.conf httpd.conf

CMD ["/busybox-httpd", "-f", "-v", "-p", "3000", "-c", "httpd.conf"]
